[general]
working_directory = "None"
import = [
    "gruvbox_dark.toml",
    "font.toml",
    "bindings.toml",
]

[font]
size = 14.0

[scrolling]
history = 10000

[terminal.shell]
program = "zsh"

[env]
SHELL = "/usr/bin/zsh"

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
# opacity = 1
startup_mode = "Maximized"
title = "Alacritty"
[window.class]
general = "Alacritty"
instance = "Alacritty"
# [window.dimensions]
# columns = 120
# lines = 40
# [window.position]
# x = 0
# y = 0
